# Example Energy Panel Card Configuration

type: custom:ha-energy-panel
title: Energy Consumption
power_entity: sensor.energy_power_data
gas_entity: sensor.energy_gas_data
dates_entity: sensor.energy_available_dates
date_input: input_datetime.energy_chart_date
