# Example automation to update energy sensors when date changes

automation:
  - alias: Update Energy Data When Date Changes
    description: Updates power and gas data when the date selection changes
    trigger:
      - platform: state
        entity_id: input_datetime.energy_chart_date
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.energy_power_data
      - service: homeassistant.update_entity
        entity_id: sensor.energy_gas_data
